Obsessedantag
funky-station/funky-station pull request #3
Opened 2024-08-28 03:46 UTC by taydeo

## About the PR

Adds a new antag called the Obsessed. Can be created through a random event.

## Why / Balance

More flavor antags need to be added to the game, and this is just a part in doing that.

## Technical details

Several things were added, such as a new proximity objective, a persistent target objective and more.

## Media

No media

## Requirements

- [X] I have read and I am following the [Pull Request Guidelines](https://docs.spacestation14.com/en/general-development/codebase-info/pull-request-guidelines.html). I understand that not doing so may get my pr closed at maintainer’s discretion
- [X] I have added screenshots/videos to this PR showcasing its changes ingame, **or** this PR does not require an ingame showcase

## Breaking changes

None so far.

**Changelog**

:cl:
- add: Added the Obsessed antagonist. https://tgstation13.org/wiki/Obsessed

2025-05-13 22:30 UTC, SolsticeOfTheWinter commented on Content.Server/_Funkystation/Obsessed/Objectives/Components/HuggingObjectiveConditionComponent.cs
> +    [DataField, ViewVariables(VVAccess.ReadWrite)]
Datafield inherently marks a variable as viewvariables-able no?

2025-05-13 22:30 UTC, SolsticeOfTheWinter commented on Content.Server/_Funkystation/Obsessed/GameTicking/ObsessedRuleSystem.cs
> +    public readonly SoundSpecifier BriefingSound = new SoundPathSpecifier("/Audio/_Funkystation/Ambience/obsessed.ogg");
Move this into the component.

2025-05-13 22:31 UTC, SolsticeOfTheWinter commented on Content.Server/_Funkystation/Obsessed/GameTicking/ObsessedRuleSystem.cs
> +    public bool MakeObsessed(EntityUid target, ObsessedRuleComponent rule)
Naming should be "TryMakeObsessed" if it can return a bool.

2025-05-13 22:31 UTC, SolsticeOfTheWinter commented on Content.Server/_Funkystation/Obsessed/GameTicking/ObsessedRuleSystem.cs
> +            if (!_mind.TryGetMind(ling.Owner, out var mindId, out var mind))
Combine these into one if statement. Looks cleaner.

2025-05-13 22:31 UTC, SolsticeOfTheWinter commented on Content.Server/_Funkystation/Obsessed/GameTicking/ObsessedRuleSystem.cs
> +        var mostAbsorbed = 0f;
>most absorbed
kek

2025-05-13 22:32 UTC, SolsticeOfTheWinter commented on Content.Server/_Funkystation/Obsessed/GameTicking/ObsessedRuleSystem.cs
> +            if (!TryComp<MetaDataComponent>(ling.Owner, out var metaData))
Trycomping a metadata?

2025-05-13 22:33 UTC, SolsticeOfTheWinter commented on Content.Server/_Funkystation/Obsessed/GameTicking/ObsessedRuleSystem.cs
> +        obsessedComponent.HugAmount = 0f;
Why initialize this at zero if it's set to zero in the component by default? Seems redundant.

2025-05-13 22:33 UTC, SolsticeOfTheWinter commented on Content.Server/_Funkystation/Obsessed/GameTicking/ObsessedRuleSystem.cs
> +            _mind.TryRemoveObjective(mindId, mindComponent, i);
Useless brackets

2025-05-13 22:33 UTC, SolsticeOfTheWinter commented on Content.Server/_Funkystation/Obsessed/Objectives/Components/ObsessedPersistentTarget.cs
> +    [DataField, ViewVariables(VVAccess.ReadWrite)]
Same as above. No need for viewvariables if its a datafield.

2025-05-13 22:33 UTC, SolsticeOfTheWinter commented on Content.Server/_Funkystation/Obsessed/Objectives/Components/RandomPersistentTargetComponent.cs
> +{
End it with a ; instead of making empty brackets.

2025-05-13 22:33 UTC, SolsticeOfTheWinter commented on Content.Server/_Funkystation/Obsessed/Objectives/Components/TargetProximityConditionComponent.cs
> +{
Same as above.

2025-05-13 22:35 UTC, SolsticeOfTheWinter commented on Content.Server/_Funkystation/Obsessed/Objectives/Systems/ClosenessObjectiveSystem.cs
> +        _query = _entityManager.EntityQueryEnumerator<HumanoidAppearanceComponent>();
Why are you using the entity manager to get a query here?

2025-05-13 22:36 UTC, SolsticeOfTheWinter commented on Content.Server/_Funkystation/Obsessed/Objectives/Systems/ClosenessObjectiveSystem.cs
> +        while (_query.MoveNext(out var humanoid, out _))
Performing a query on EVERY humanoid, then checking if they are in range seems a bit expensive no?
I feel like it'd be more efficient to use LookUpSystem and check only entities in range.

2025-05-13 22:36 UTC, SolsticeOfTheWinter commented on Content.Server/_Funkystation/Obsessed/Objectives/Systems/ClosenessObjectiveSystem.cs
> +                return;
```suggestion
                continue;
```

2025-05-13 22:37 UTC, SolsticeOfTheWinter commented on Content.Server/_Funkystation/Obsessed/Objectives/Systems/ClosenessObjectiveSystem.cs
> +    private void ProximityCheck(EntityUid? entity, ObsessedComponent? component)
```suggestion
    private void ProximityCheck(EntityUid? entityNullable, ObsessedComponent? component)
```

2025-05-13 22:37 UTC, SolsticeOfTheWinter commented on Content.Server/_Funkystation/Obsessed/Objectives/Systems/ClosenessObjectiveSystem.cs
> +            if (entity != null && !_examineSystem.InRangeUnOccluded(entity.Value, humanoid, 32F))
```suggestion
            if (entityNullable is not { } entity && !_examineSystem.InRangeUnOccluded(entity, humanoid, 32F))
```

2025-05-13 22:38 UTC, SolsticeOfTheWinter commented on Content.Server/_Funkystation/Obsessed/Objectives/Systems/ClosenessObjectiveSystem.cs
> +            var ev = new PlayerProximityEvent(entity!.Value, component.UpdateTimeInterval);
```suggestion
            var ev = new PlayerProximityEvent(entity, component.UpdateTimeInterval);
```

2025-05-13 22:38 UTC, SolsticeOfTheWinter commented on Content.Server/_Funkystation/Obsessed/Objectives/Systems/ClosenessObjectiveSystem.cs
> +            RaiseLocalEvent(entity.Value, ref ev);
```suggestion
            RaiseLocalEvent(entity, ref ev);
```

2025-05-13 22:39 UTC, SolsticeOfTheWinter commented on Content.Server/_Funkystation/Obsessed/Objectives/Systems/ObsessedHuggingSystem.cs
> +        if (!TryComp<ObsessedPersistentTargetComponent>(args.Mind.OwnedEntity, out var targetComponent))
Again, these should be one if statement not two.

2025-05-13 22:39 UTC, SolsticeOfTheWinter commented on Content.Server/_Funkystation/Obsessed/Objectives/Systems/ObsessedHuggingSystem.cs
> +            obsessedComponent.CompletedObjectives.Add("ObsessedHuggingCondition", true);
Useless brackets?

2025-05-13 22:40 UTC, SolsticeOfTheWinter commented on Content.Server/_Funkystation/Obsessed/Objectives/Systems/TargetProximityConditionSystem.cs
> +    {
Useless brackets

2025-05-13 22:40 UTC, SolsticeOfTheWinter commented on Content.Server/_Funkystation/Roles/ObsessedRole.cs
> +{
Useless brackets

2025-05-13 22:40 UTC, SolsticeOfTheWinter commented on Content.Shared/Funkystation/Obsessed/ObsessedComponent.cs
> +    [DataField, ViewVariables(VVAccess.ReadWrite)]
Again, you don't need ViewVariables if you made it a datafield.

2025-05-13 22:40 UTC, SolsticeOfTheWinter commented on Content.Shared/Funkystation/Obsessed/ObsessedComponent.cs
> +    public TimeSpan NextUpdateTime = TimeSpan.Zero;
No need to initialize this as zero.

2025-05-13 22:41 UTC, SolsticeOfTheWinter commented on Content.Shared/Interaction/InteractionPopupSystem.cs
> +                    && TryComp<MetaDataComponent>(uid, out var meta)
You don't need to trycomp a metadata component. If something has no metadata component you've got bigger issues.

2025-05-13 22:42 UTC, SolsticeOfTheWinter requested changes
This needs work, but it has potential.

2025-05-13 22:43 UTC, SolsticeOfTheWinter commented
Also, your linter is failing.

2025-05-14 02:42 UTC, taydeo commented
forgot about this pr

2025-11-09 08:04 UTC, Reithauky commented
In ss13, mindshield didn't prevent one becoming obsessed,the captain could roll obsessed, as it was the person going mental and not an outside mind control

Is this what it'll be here?

2026-01-10 21:48 UTC, Komonighub commented
@taydeo when's this coming out

2026-01-11 00:36 UTC, taydeo commented
hell naw

2026-01-11 00:36 UTC, closed without merging

2026-04-22 20:05 UTC, JohnnyDangerSpace4 commented
sub8 aura mogged host closes pr in shitcode shame